import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Theme, ThemePanel } from "@radix-ui/themes";
import Navbar from "@/app/components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Theme
          accentColor="purple"
          grayColor="sage"
          panelBackground="solid"
          radius="large"
        >
          <Navbar />
          <main className="max-w-7xl mx-auto min-h-full">{children}</main>
        </Theme>
      </body>
    </html>
  );
}
